theme: minima
show_excerpts: false
locale: en_GB

minima:
  date_format: "%b %-d, %Y"

sass:
  style: compressed
  sass_dir: _sass

exclude:
  - .jekyll-cache

plugins:
  - jekyll-include-cache
  - jekyll-webp

data_dir: data
############################################################
# Site configuration for the WebP Generator Plugin
webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 100

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/images", "/images/upload"]

  # Whether to search in nested directories or not
  nested: true

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################

permalink: /:year-:month-:day-:slug'


include: 
  - _redirects
  - _headers
  

title: Tax Reclaimed
url: "https://www.taxreclaimed.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
description: For life insurance, equity release and more, find the financial help you need in a matter of minutes.
logo: /images/logo.png
logo_footer: /images/logo-white.png

twitter_url: https://www.twitter.com/TaxReclaimedUK
facebook_url: https://www.facebook.com/taxreclaimeduk
linkedin_url: https://www.linkedin.com/company/tax-reclaimed/
youtube_url: https://www.youtube.com/channel/UCuyy3OjfnisE8hCp43qxVaw

# Settings for your Storyblok space
storyblok:
  token: "EcLhw8tBkVHm2Wz27h2EPAtt"
  # Can be either `draft` or `published`
  version: draft

hide_address: true


